
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_REGISTED = 'USER_REGISTED'
export const USER_CANCEL_LOGIN = 'USER_CANCEL_LOGIN'
export const USER_KICKED = 'USER_KICKED'

export const CONFIRM_EMAIL = 'CONFIRM_EMAIL'
export const RESEND_EMAIL = 'RESEND_EMAIL'

export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL'
export const FETCH_USER_PACKAGES = 'FETCH_USER_PACKAGES'

export const FETCH_ALL_BOTS = 'FETCH_ALL_BOTS'
export const FETCH_BOT_INFO = 'FETCH_BOT_INFO'
export const FETCH_BOT_HISTORY = 'FETCH_BOT_HISTORY'
export const FETCH_BOT_MATCHING = 'FETCH_BOT_MATCHING'
export const FETCH_BOT_REPORT = 'FETCH_BOT_REPORT'
export const FETCH_SUPPORT_PLATFORMS = 'FETCH_SUPPORT_PLATFORMS'
export const FETCH_FACEBOOK = 'FETCH_FACEBOOK'
export const FETCH_LINE = 'FETCH_LINE'
export const FETCH_FACEBOOK_IGNORE = 'FETCH_FACEBOOK_IGNORE'
export const FETCH_LINE_IGNORE = 'FETCH_LINE_IGNORE'

export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL'
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD'

export const CREATE_BOT = 'CREATE_BOT'
export const DELETE_BOT = 'DELETE_BOT'
export const UPDATE_BOT = 'UPDATE_BOT'

export const CREATE_QUESTION = 'CREATE_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'

export const CREATE_ANSWER = 'CREATE_ANSWER'
export const UPDATE_ANSWER = 'UPDATE_ANSWER'
export const DELETE_ANSWER = 'DELETE_ANSWER'

export const DELETE_GROUP = 'DELETE_GROUP'
export const FETCH_GROUPS = 'FETCH_GROUPS'
export const FETCH_GROUP = 'FETCH_GROUP'
export const UPLOAD_GROUPS = 'DELETE_GROUPS'
export const EXPORT_GROUPS = 'EXPORT_GROUPS'
export const TRAIN_GROUPS = 'TRAIN_GROUPS'
export const FETCH_GROUP_LENGTH = 'FETCH_GROUP_LENGTH'

export const FETCH_AGENT = 'FETCH_AGENT'
export const CREATE_AGENT = 'CREATE_AGENT'
export const UPDATE_AGENT = 'UPDATE_AGENT'
export const DELETE_AGENT = 'DELETE_AGENT'
export const CREATE_AGENT_MEMBER = 'CREATE_AGENT_MEMBER'
export const UPDATE_AGENT_MEMBER = 'UPDATE_AGENT_MEMBER'
export const FETCH_AGENT_MEMBER = 'FETCH_AGENT_MEMBER'
export const FETCH_AGENT_MEMBER_DETAIL = 'FETCH_AGENT_MEMBER_DETAIL'
export const FETCH_AGENT_ALL_MEMBERS = 'FETCH_AGENT_ALL_MEMBERS'

export const AGENT_LOGGED_IN = 'LOGIN_AGENT'
export const AGENT_LOGGED_OUT = 'LOGOUT_AGENT'

export const SET_GLOBAL_MESSAGE = 'SET_GLOBAL_MESSAGE'

export const FETCH_TASKBOTS = 'FETCH_TASKBOTS'
export const FETCH_TASKBOT = 'FETCH_TASKBOT'
export const CREATE_TASKBOT = 'CREATE_TASKBOT'
export const UPDATE_TASKBOT = 'UPDATE_TASKBOT'
export const DELETE_TASKBOT = 'DELETE_TASKBOT'