# Generated by Django 2.1.3 on 2018-11-13 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acctype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True)),
                ('expire_date', models.DateTimeField(blank=True)),
                ('free_package_used', models.BooleanField(default=False)),
                ('confirmation_code', models.CharField(max_length=255)),
                ('code_reset_time', models.DateTimeField()),
                ('code_send_times', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('cn', 'cn'), ('tw', 'tw'), ('en', 'en')], default='tw', max_length=10)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_type', to='acctype.PaidType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
    ]
