# Generated by Django 2.1.3 on 2018-11-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='language',
            field=models.CharField(choices=[('cn', 'cn'), ('en', 'en'), ('tw', 'tw')], default='tw', max_length=10),
        ),
    ]
