# Generated by Django 2.1.3 on 2018-11-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181113_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
