# Generated by Django 2.1.3 on 2018-11-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181113_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='free_package_used',
        ),
    ]
