# Generated by Django 2.1.3 on 2018-11-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thirdparty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('bot_amount', models.CharField(max_length=100)),
                ('faq_amount', models.CharField(max_length=100)),
                ('thirdparty', models.ManyToManyField(related_name='paid_party', to='thirdparty.ThirdParty')),
            ],
            options={
                'db_table': 'paid_type',
            },
        ),
    ]
