# Generated by Django 2.1.3 on 2018-11-13 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=100)),
                ('greeting_msg', models.TextField(blank=True, null=True)),
                ('failed_msg', models.TextField(blank=True, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('cn', 'cn'), ('tw', 'tw'), ('en', 'en')], default='tw', max_length=10)),
                ('postback_title', models.CharField(default='請選擇跟你問題類似的問題，如果沒有請繼續問其他問題。', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot',
            },
        ),
    ]
