# Generated by Django 2.1.3 on 2018-11-13 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thirdparty', '0002_auto_20181113_0431'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotThirdPartyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bot_third_party_group',
            },
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='language',
            field=models.CharField(choices=[('cn', 'cn'), ('en', 'en'), ('tw', 'tw')], default='tw', max_length=10),
        ),
        migrations.AddField(
            model_name='botthirdpartygroup',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chatbot', to='chatbot.Chatbot'),
        ),
        migrations.AddField(
            model_name='botthirdpartygroup',
            name='thirdparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_thirdparty', to='thirdparty.ThirdParty'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='third_party',
            field=models.ManyToManyField(related_name='group_bot_party', through='chatbot.BotThirdPartyGroup', to='thirdparty.ThirdParty'),
        ),
    ]
